// Generated by CoffeeScript 1.6.0
(function() {
  var optimizer;

  optimizer = function() {
    var makeButton;
    makeButton = function(solution) {
      var elem;
      elem = document.createElement('input');
      elem.addEventListener('click', function() {
        return chrome.runtime.sendMessage({
          solution: solution,
          type: 'addToCart'
        });
      }, false);
      elem.type = 'input';
      elem.setAttribute('type', 'button');
      elem.className = 'button';
      elem.style.float = 'right';
      elem.value = 'カートに入れる';
      return elem;
    };
    return new MutationObserver(function(mutations) {
      var solution, table, tr, url, _i, _len, _ref, _results;
      table = mutations.pop().addedNodes[0];
      if (!table) {
        return;
      }
      solution = [];
      _ref = table.firstChild.children;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        tr = _ref[_i];
        if (tr.firstChild.tagName.toUpperCase() === 'TH') {
          _results.push(solution = []);
        } else if (tr.firstChild.getAttribute('colspan')) {
          _results.push(tr.firstChild.appendChild(makeButton(solution)));
        } else {
          url = tr.querySelector('a[href*="store.asp"]').href;
          _results.push(solution.push({
            storeId: /sID=(\w+)/.exec(url)[1],
            lotId: /itemID=(\w+)/.exec(url)[1],
            amount: tr.children[3].textContent | 0
          }));
        }
      }
      return _results;
    }).observe(document.getElementById('result'), {
      childList: true
    });
  };

  (function() {
    var handler, re, routes, _i, _len, _ref, _results;
    routes = [[/optimizer/, optimizer]];
    _results = [];
    for (_i = 0, _len = routes.length; _i < _len; _i++) {
      _ref = routes[_i], re = _ref[0], handler = _ref[1];
      if (re.test(location.pathname)) {
        _results.push(handler());
      }
    }
    return _results;
  })();

}).call(this);
